"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { ScrollReveal } from "./ScrollReveal";

const faqs = [
  {
    question: "How does the AI analysis work?",
    answer:
      "ChurnAuditor uses a two-stage Gemini AI pipeline. First, Gemini Flash performs rapid triage to assess urgency and save probability. For high-value cases, Gemini Pro runs a deep diagnosis — analyzing support tickets, usage patterns, and exit survey data to determine the root cause with confidence scoring.",
  },
  {
    question: "Do I need a Gemini API key?",
    answer:
      "No! ChurnAuditor works in full demo mode without any API keys. The demo fallback uses deterministic mock scenarios that produce consistent, realistic results. Add your Gemini API key when you're ready for real AI-powered analysis.",
  },
  {
    question: "What Stripe events does it capture?",
    answer:
      "ChurnAuditor listens for `customer.subscription.deleted` webhook events. When a subscription is cancelled, it automatically extracts customer details, MRR, plan information, and cancellation reason to feed into the AI diagnosis pipeline.",
  },
  {
    question: "Can I customize the recovery actions?",
    answer:
      "Currently, ChurnAuditor supports four recovery actions: winback emails, Linear ticket creation, Slack alerts, and manual review flagging. Each action is generated by AI based on the specific churn diagnosis. The integration layer is modular — swap in your own email provider, ticket system, or messaging platform.",
  },
  {
    question: "Is this production-ready?",
    answer:
      "ChurnAuditor is a hackathon MVP that demonstrates the full AI-powered churn recovery pipeline. It uses an in-memory store (resets on deploy) and mock integrations. For production: add a database (Supabase/Postgres), configure real Stripe webhooks, and connect live integrations.",
  },
  {
    question: "How fast is the analysis?",
    answer:
      "In demo mode, analysis completes in 3-5 seconds. With real Gemini AI, triage takes ~2 seconds and deep diagnosis ~15-20 seconds. The entire pipeline — from webhook to executed recovery actions — typically completes in under 60 seconds.",
  },
];

export function FAQ() {
  return (
    <section id="faq" className="relative py-32 px-6">
      <div className="mx-auto max-w-3xl">
        <ScrollReveal>
          <div className="mb-12 text-center">
            <p className="mb-3 text-sm font-medium uppercase tracking-widest text-muted-foreground">
              FAQ
            </p>
            <h2 className="text-4xl font-bold tracking-tight sm:text-5xl">
              Common Questions
            </h2>
          </div>
        </ScrollReveal>

        <ScrollReveal delay={0.2}>
          <Accordion type="single" collapsible className="space-y-3">
            {faqs.map((faq, i) => (
              <AccordionItem
                key={i}
                value={`item-${i}`}
                className="glass-card-landing overflow-hidden rounded-xl border-0 px-6"
              >
                <AccordionTrigger className="py-5 text-left text-base font-medium hover:no-underline">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="pb-5 text-sm leading-relaxed text-muted-foreground">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </ScrollReveal>
      </div>
    </section>
  );
}
